name = "Spawn Lanterns ğŸ®"
filename = "spawnlanterns-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3125/142/spawnlanterns-1.0.1.jar"
hash-format = "murmur2"
hash = "360005652"

[update]
[update.curseforge]
file-id = 3125142
project-id = 418565
release-channel = "beta"
